import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";

const clerkPubKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (!clerkPubKey) throw new Error("Missing Clerk publishable key!");
  return (
    <html lang="en">
      <ClerkProvider publishableKey={clerkPubKey}>
        <body className="antialiased">
          <SidebarProvider>{children}</SidebarProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
